services:
  - type: web
    name: testlink
    env: docker
    image: bitnami/testlink:latest
    ports:
      - 8080
    envVars:
      - key: TESTLINK_USERNAME
        value: admin
      - key: TESTLINK_PASSWORD
        value: bitnami123
      - key: TESTLINK_EMAIL
        value: admin@example.com
      - key: MARIADB_HOST
        value: testlink-db
      - key: TESTLINK_DATABASE_USER
        value: bn_testlink
      - key: TESTLINK_DATABASE_NAME
        value: bitnami_testlink
      - key: TESTLINK_DATABASE_PASSWORD
        value: bitnami123
    dependsOn:
      - testlink-db

  - type: web
    name: testlink-db
    env: docker
    image: bitnami/mariadb:latest
    envVars:
      - key: MARIADB_USER
        value: bn_testlink
      - key: MARIADB_PASSWORD
        value: bitnami123
      - key: MARIADB_DATABASE
        value: bitnami_testlink
      - key: ALLOW_EMPTY_PASSWORD
        value: "yes"

  - type: web
    name: mantisbt
    env: docker
    image: bitnami/mantisbt:latest
    ports:
      - 8081
    envVars:
      - key: MANTISBT_DATABASE_HOST
        value: mantis-db
      - key: MANTISBT_DATABASE_NAME
        value: bitnami_mantis
      - key: MANTISBT_DATABASE_USER
        value: bn_mantis
      - key: MANTISBT_DATABASE_PASSWORD
        value: bitnami123
      - key: MANTISBT_USERNAME
        value: admin
      - key: MANTISBT_PASSWORD
        value: admin123
      - key: MANTISBT_EMAIL
        value: admin@example.com
    dependsOn:
      - mantis-db

  - type: web
    name: mantis-db
    env: docker
    image: bitnami/mariadb:latest
    envVars:
      - key: MARIADB_USER
        value: bn_mantis
      - key: MARIADB_PASSWORD
        value: bitnami123
      - key: MARIADB_DATABASE
        value: bitnami_mantis
      - key: ALLOW_EMPTY_PASSWORD
        value: "yes"
